PETSC_DIR=/grand/alcf_training/HandsOnHPC24/petsc
CFLAGS           =
FFLAGS           =
CPPFLAGS         =
FPPFLAGS         =
EXAMPLESC        = multidim_rosenbrock.c ex19.c
EXAMPLESF        =
EXAMPLESCH       =
EXAMPLESFH       =
LOCDIR           =
MANSEC           =
DOCS             =
DIRS             =
CLEANFILES   = multidim_rosenbrock ex19

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
