#!/bin/bash

module load conda/2021-09-22
conda activate

NODES=$1

export HOROVOD_HIERARCHICAL_ALLREDUCE=0
export HOROVOD_HIERARCHICAL_ALLGATHER=1
export HOROVOD_CACHE_CAPACITY=1024 
export HOROVOD_CYCLE_TIME=2.10061
export HOROVOD_FUSION_THRESHOLD=4.92817

export HOROVOD_TIMELINE=timeline_gpu_n${NODES}.json

mpirun -x HOROVOD_HIERARCHICAL_ALLREDUCE -x HOROVOD_HIERARCHICAL_ALLGATHER -x HOROVOD_CACHE_CAPACITY \
	-x HOROVOD_CYCLE_TIME -x  HOROVOD_FUSION_THRESHOLD -x LD_LIBRARY_PATH -x PYTHONPATH -x PATH  --hostfile ${COBALT_NODEFILE} \
	-x HOROVOD_TIMELINE -x HOROVOD_TIMELINE_MARK_CYCLES=1 \
        -n $NODES  -npernode 8 python ../../tensorflow2_mnist.py --device gpu --epochs 10 >& gpu_n${NODES}_timeline.out

