#!/bin/bash

module load conda/2021-09-22
conda activate

NODES=$1

export HOROVOD_HIERARCHICAL_ALLREDUCE=0
export HOROVOD_HIERARCHICAL_ALLGATHER=1
export HOROVOD_CACHE_CAPACITY=1024 
export HOROVOD_CYCLE_TIME=2.10061
export HOROVOD_FUSION_THRESHOLD=4.92817

mpirun -x HOROVOD_HIERARCHICAL_ALLREDUCE -x HOROVOD_HIERARCHICAL_ALLGATHER -x HOROVOD_CACHE_CAPACITY \
	-x HOROVOD_CYCLE_TIME -x  HOROVOD_FUSION_THRESHOLD -x LD_LIBRARY_PATH -x PYTHONPATH -x PATH  --hostfile ${COBALT_NODEFILE}\
       -n $NODES  -npernode 8 python ../../tensorflow2_mnist.py --device gpu --epochs 100 >& gpu_n${NODES}_evaluate.out

